name: markey
description: A new Flutter project.

publish_to: "none"

version: 0.0.5+5

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.1+1
  flutter_staggered_grid_view: ^0.6.2
  rating_dialog: ^2.0.4

  image_picker: ^0.8.6
  image_cropper: ^3.0.1
  qr_flutter: ^4.0.0
  webview_flutter: ^4.0.2

  timeago: ^3.2.2
  intl: ^0.17.0

  get: ^4.6.5
  get_storage: ^2.0.3

  chopper: ^4.0.6
  logging: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  device_preview: ^1.1.0

  build_runner: ^2.1.11
  chopper_generator: ^4.0.6

  flutter_launcher_icons: ^0.9.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
